apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-custom-rules
  namespace: infra-falco
data:
  custom_rules.yaml: |
    # --------------------------------------------------------------------------------
    # 1. Detect Shell Activity in Containers
    # --------------------------------------------------------------------------------
    - rule: Shell in Container
      desc: Notice shell activity within a container
      condition: >
        spawned_process and container and
        (proc.name in (shell_binaries) or
         (proc.name in (shell_interpreters) and not proc.args contains "entrypoint"))
        and not k8s.ns.name in ("kube-system", "monitoring")
      output: >
        Shell spawned in container (user=%user.name %container.info
        shell=%proc.name parent=%proc.pname cmdline=%proc.cmdline k8s.ns=%k8s.ns.name k8s.pod=%k8s.pod.name)
      priority: WARNING
      tags: [container, shell]

    # --------------------------------------------------------------------------------
    # 2. Detect Write to Sensitive Files
    # --------------------------------------------------------------------------------
    - rule: Write Below Etc
      desc: Write to sensitive directory /etc
      condition: >
        write_etc_common and not proc.name in (package_mgmt_binaries) 
        and not proc.name in ("systemd", "sed", "bash", "sh")
        and not k8s.ns.name in ("kube-system")
      output: >
        File below /etc opened for writing (user=%user.name command=%proc.cmdline 
        file=%fd.name parent=%proc.pname pcmdline=%proc.pcmdline k8s.ns=%k8s.ns.name k8s.pod=%k8s.pod.name)
      priority: ERROR
      tags: [filesystem, mitre_persistence]

    # --------------------------------------------------------------------------------
    # 3. Detect Network Connections from Containers
    # --------------------------------------------------------------------------------
    - rule: Outbound Connection to C2 Servers
      desc: Detect outbound connections to suspicious IPs
      condition: >
        outbound and fd.typechar=4 and fd.ip != "127.0.0.1" and fd.ip != "::1"
        and not proc.name in ("curl", "wget", "http", "https")
        and not k8s.ns.name in ("kube-system", "monitoring", "flux-system")
        and fd.sport > 32000
      output: >
        Outbound connection to suspicious destination (user=%user.name command=%proc.cmdline 
        connection=%fd.name k8s.ns=%k8s.ns.name k8s.pod=%k8s.pod.name)
      priority: WARNING
      tags: [network, mitre_command_and_control]
