apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: infra-falco
spec:
  interval: 1m
  chart:
    spec:
      chart: falco
      version: "6.0.0"
      sourceRef:
        kind: HelmRepository
        name: falco
        namespace: flux-system

  releaseName: falco
  targetNamespace: infra-falco
