apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: infra-falco
spec:
  interval: 1m
  chart:
    spec:
      chart: falco
      version: "6.0.0"
      sourceRef:
        kind: HelmRepository
        name: falco
        namespace: flux-system

  releaseName: falco
  targetNamespace: infra-falco
  timeout: 3m

  values:
    falco:
      rules_files:
        - /etc/falco/falco_rules.yaml
        - /etc/falco/falco_rules.local.yaml
        - /etc/falco/custom_rules.yaml

    # Mount the ConfigMap
    mounts:
      volumes:
        - name: custom-rules
          configMap:
            name: falco-custom-rules
      volumeMounts:
        - name: custom-rules
          mountPath: /etc/falco/custom_rules.yaml
          subPath: custom_rules.yaml
