apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  labels:
    app.kubernetes.io/name: falco
    app.kubernetes.io/part-of: infra-falco
  namespace: flux-system
spec:
  interval: 10m
  releaseName: falco
  targetNamespace: infra-falco
  chart:
    spec:
      chart: falco
      version: 0.41.1
      sourceRef:
        kind: HelmRepository
        name: infra-falco
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
