apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: infra-falco
spec:
  interval: 1m
  chart:
    spec:
      chart: falco
      version: "6.0.0"
      sourceRef:
        kind: HelmRepository
        name: falco
        namespace: flux-system

  releaseName: falco
  targetNamespace: infra-falco
  timeout: 15m

  values:
    falco:
      rules_file:
        - /etc/falco/falco_rules.yaml
        - /etc/falco/falco_rules.local.yaml
        - /etc/falco/custom_rules.yaml # Add your custom rules

    # Mount the ConfigMap
    extraVolumes:
      - name: custom-rules
        configMap:
          name: falco-rules

    extraVolumeMounts:
      - name: custom-rules
        mountPath: /etc/falco/custom_rules.yaml
        subPath: custom_rules.yaml
