---
- name: Install containerd
  become: yes
  raw: pacman -Sy --noconfirm containerd

- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Generate default containerd config
  shell: containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

- name: Enable and start containerd
  systemd:
    name: containerd
    enabled: yes
    state: started
