apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium
spec:
  controllerName: io.cilium/gateway-controller
  parametersRef:
    group: io.cilium.gateway
    kind: CiliumGatewayConfig
    name: cilium-gateway-config
