apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: cilium
      version: 1.17.3
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  values:
    kubeProxyReplacement: true
    k8sServiceHost: archcore-control.lab.local
    k8sServicePort: 6443

    ingressController:
      enabled: true
      default: true
      loadbalancerMode: dedicated
      ingressClassName: cilium
