apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: cilium
      version: 1.17.3
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  values:
    kubeProxyReplacement: "strict"
    k8sServiceHost: archcore-control.lab.local
    k8sServicePort: 6443
    ipam:
      mode: kubernetes # Ensure this is set if not already default

    # externalIPs: # Keep if you need Cilium's externalIPs management
    #   enabled: true

    # loadBalancerIPs: # Keep if you need Cilium's loadBalancerIPs management
    #   enabled: true

    l2announcements:
      enabled: true
      interface: enp1s0

    ciliumIngress:
      enabled: false # Consider disabling if you're primarily using standard Ingress and/or Gateway API

    operator:
      enabled: true
      manageCRDs: true

    ingressController:
      enabled: true
      default: true
      loadbalancerMode: dedicated
      ingressClassName: cilium
      service:
        enabled: true
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "192.168.178.240"
          io.cilium/lb-ipam-mode: "pool"
        externalTrafficPolicy: Local

    gatewayAPI:
      enabled: true
