apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: cluster-pool
spec:
  blocks:
    - start: "192.168.68.20"
      stop: "192.168.68.20"
  serviceSelector:
    matchExpressions:
      - key: io.kubernetes.service.namespace
        operator: In
        values:
          - default
          - infra-gateway
#
