apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-announcement-policy
spec:
  nodeSelector: {}
  interfaces:
    - enp2s0
    - enp1s0
    - eno1
    - eth0
  externalIPs: true
  loadBalancerIPs: true
