apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: cluster-pool
spec:
  blocks:
    - start: "192.168.178.240"
      stop: "192.168.178.245"
  serviceSelector:
    matchExpressions:
      - key: io.kubernetes.service.namespace
        operator: In
        values:
          - default
          - hypercube-test
          - infra-longhorn
