apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: ca-cert
          secret:
            secretName: harbor-ca-cert
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          mountPath: /etc/ssl/certs/harbor-ca.crt # Or similar path
          name: ca-cert
          subPath: ca.crt
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: REQUESTS_CA_FILE # Flux's way to specify custom CAs for Go HTTP clients
          value: /etc/ssl/certs/harbor-ca.crt
    target:
      kind: Deployment
      name: source-controller
      namespace: flux-system # Ensure this matches
