apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prom-stack
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  retryInterval: 2m
  wait: false
  path: ./apps/prom-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: infra-namespaces
    - name: infra-storage-pvcs
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kube-prometheus-stack-operator
      namespace: prom-stack
    - apiVersion: apps/v1
      kind: Deployment
      name: kube-prometheus-stack-grafana
      namespace: prom-stack
