apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-system
  namespace: flux-system
spec:
  interval: 10m
  timeout: 3m
  retryInterval: 1m
  wait: false
  path: ./apps/cnpg-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: infra-namespaces
    - name: openebs
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cloudnative-pg
      namespace: cnpg-system
