apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dashy
  namespace: flux-system
spec:
  interval: 10m
  timeout: 3m
  retryInterval: 1m
  wait: false
  path: ./apps/dashy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: infra-namespaces
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: dashy
      namespace: dashy
