apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: open-webui
  namespace: flux-system
spec:
  interval: 10m
  timeout: 3m
  retryInterval: 1m
  wait: false
  path: ./apps/open-webui
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: infra-namespaces
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: open-webui
      namespace: open-webui
    - apiVersion: apps/v1
      kind: Deployment
      name: open-webui-pipelines
      namespace: open-webui
