apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qdrant
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  retryInterval: 2m
  wait: true
  path: ./apps/qdrant
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: openebs
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: qdrant
      namespace: qdrant
