apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: n8n
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/n8n
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
