apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-ks-patches
  namespace: flux-system
spec:
  interval: 1m
  path: ./infrastructure/kube-system-patches
  prune: true
  dependsOn:
  - name: cilium
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system