apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph-details
  namespace: flux-system
spec:
  interval: 10m
  timeout: 10m
  retryInterval: 2m
  wait: false
  path: ./infrastructure/rook-ceph-details
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: rook-ceph
  healthChecks:
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      name: rook-ceph
      namespace: rook-ceph
