apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-gateways
  namespace: flux-system
spec:
  interval: 10m
  timeout: 3m
  retryInterval: 1m
  wait: true
  path: ./infrastructure/gateways
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      name: public-gateway
      namespace: infra-gateway
  dependsOn:
    - name: infra-certmgr-deploy
