apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-gateways
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/https_routes
  prune: true
  dependsOn:
    - name: infra-gateways
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
