apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-kube-metrics
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/kube-state-metrics
  prune: true
  dependsOn:
    - name: infra-vm
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
