apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-certmgr-deploy
  namespace: flux-system
spec:
  interval: 10m
  releaseName: cm
  path: ./infrastructure/cert-manager/deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: infra-cilium
