apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-flux-system
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/flux-system
  prune: true
  dependsOn:
    - name: infra-cilium
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
