apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: hypercube-gateway
  namespace: hypercube-test
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-route
  namespace: hypercube-test
spec:
  parentRefs:
    - name: hypercube-gateway
  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: nginx
          port: 80
