apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cadvisor
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/cadvisor
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
