apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cilium
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  retryInterval: 2m
  wait: true
  path: ./infrastructure/cilium
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: infra-namespaces
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: cilium
      namespace: kube-system
    - apiVersion: apps/v1
      kind: DaemonSet
      name: cilium-envoy
      namespace: kube-system
    - apiVersion: apps/v1
      kind: Deployment
      name: cilium-operator
      namespace: kube-system
