apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: falco
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  retryInterval: 2m
  wait: true
  path: ./infrastructure/falco
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: falco
      namespace: infra-falco
