apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-storage-pvcs
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/storage
  prune: false # Disable pruning to retain PVCs
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: openebs
    - name: rook-ceph-details
