apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-node-patches
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/lab/kube-node-patches
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
