apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Infrastructure
  - infra-namespaces.yaml
  - infra-flux-system.yaml
  - infra-openebs.yaml
  # - infra-cilium.yaml
  - infra-falco.yaml
  - infra-gateways.yaml
  - infra-https-routes.yaml

  # Kube system patches
  # - kube-node-patches.yaml

  # Applications
  - apps.yaml
  - apps-cnpg-system.yaml
  - apps-n8n.yaml
  - apps-pgadmin.yaml
  - apps-opencost.yaml
