apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - open-webui.yaml
  - open-webui-pipelines.yaml
  - pgadmin.yaml
  #- ubuntu-app.yaml
  #- ubuntu-app-openebs.yaml
  #- prom-stack-alertmanager.yaml
  #- prom-stack-grafana.yaml
  #- prom-stack-prometheus.yaml
