---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz
  namespace: flux-system
spec:
  chart:
    spec:
      chart: signoz
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: flux-system
      version: 0.90.1
  interval: 1m0s
  releaseName: signoz
  targetNamespace: signoz
  values:
    global:
      storageClass: rook-ceph-block

    otelCollector:
      config:
        receivers:
          filelog:
            include:
              - /var/log/pods/*/*/*.log
            exclude:
              - /var/log/pods/*/otc-container/*.log
            start_at: end
            include_file_path: true
            include_file_name: false
          k8s_events:
            auth_type: serviceAccount

        processors:
          k8sattributes:
            auth_type: serviceAccount
            passthrough: false
            extract:
              metadata:
                - k8s.pod.name
                - k8s.pod.uid
                - k8s.deployment.name
                - k8s.namespace.name
                - k8s.node.name

        service:
          pipelines:
            logs:
              receivers:
                [
                  otlp,
                  filelog,
                  k8s_events,
                  httplogreceiver/heroku,
                  httplogreceiver/json,
                ]
              processors: [k8sattributes, batch]
              exporters: [clickhouselogsexporter, metadataexporter]

    clickhouse:
      installCustomStorageClass: true
      resources:
        requests:
          cpu: "2000m"
          memory: "4Gi"
        limits:
          cpu: "4000m"
          memory: "8Gi"
      persistence:
        enabled: true
        size: 50Gi
        storageClass: rook-ceph-block

      podAnnotations:
        signoz.io/scrape: "true"
        signoz.io/port: "9363"
        signoz.io/path: /metrics

      zookeeper:
        persistence:
          enabled: true
          storageClass: rook-ceph-block
          size: 10Gi

    signoz:
      resources:
        requests:
          cpu: "1000m"
          memory: "2Gi"
        limits:
          cpu: "2000m"
          memory: "4Gi"
      persistence:
        enabled: true
        size: 10Gi
        storageClass: rook-ceph-block
