---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz
  namespace: flux-system
spec:
  chart:
    spec:
      chart: signoz
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: flux-system
      version: 0.90.1
  interval: 1m0s
  releaseName: signoz
  targetNamespace: signoz
  values:
    global:
      storageClass: openebs-signoz
      annotations:
        volume.kubernetes.io/selected-node: talos-cp-03

    clickhouse:
      installCustomStorageClass: false
      # Pin ClickHouse to the same node
      nodeSelector:
        kubernetes.io/hostname: talos-cp-03
      resources:
        requests:
          cpu: "2000m"
          memory: "8Gi"
        limits:
          cpu: "4000m"
          memory: "16Gi"
      persistence:
        enabled: true
        size: 50Gi
        annotations:
          volume.kubernetes.io/selected-node: talos-cp-03

      # Add pod annotations if needed for monitoring
      podAnnotations:
        signoz.io/scrape: "true"
        signoz.io/port: "9363"
        signoz.io/path: /metrics

    signoz:
      nodeSelector:
        kubernetes.io/hostname: talos-cp-03
      resources:
        persistence:
          enabled: true
          size: 10Gi
          annotations:
            volume.kubernetes.io/selected-node: talos-cp-03

        requests:
          cpu: "1000m"
          memory: "2Gi"
        limits:
          cpu: "2000m"
          memory: "4Gi"
