apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prom-stack
  namespace: prom-stack
spec:
  interval: 30m
  timeout: 10m
  chartRef:
    kind: OCIRepository
    name: prom-stack-oci
    namespace: flux-system
