apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateways.yaml
  - openebs.yaml
  - ai-workload.yaml
  - ollama.yaml
  - cnpg-system.yaml
  #- monitoring.yaml
  #- longhorn.yaml
  #- certmanager.yaml
  #- harbor.yaml
  #- planka.yaml
  #- opencost.yaml
  #- falco.yaml
