apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateways.yaml
  - openebs.yaml
  - cnpg-system.yaml
  - n8n.yaml
  - pgadmin.yaml
  - opencost.yaml
  - falco.yaml
  - qdrant.yaml
  - dashy.yaml
  - open-webui.yaml
  - signoz.yaml
  - rook-ceph.yaml
  - prom-stack.yaml
  - cert-manager.yaml
