apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-postgres
  namespace: n8n
spec:
  instances: 1

  # Storage configuration
  storage:
    size: 20Gi
    storageClass: openebs-hostpath

  # You can get the superuser credentials from the secret created by the Cluster
  # kubectl get secret n8n-pg-superuser -n n8n -o jsonpath='{.data.username}' | base64 -d
  # kubectl get secret n8n-pg-superuser -n n8n -o jsonpath='{.data.password}' | base64 -d

  superuserSecret:
    name: my-lab-pg-superuser

  # Database configuration if you want to create a specific database
  #bootstrap:
  #  initdb:
  #    database: n8n
  #    owner: n8n
  #    secret:
  #      name: n8n-user-secret

  # Resource limits to protect control plane
  resources:
    requests:
      memory: "1Gi"
      cpu: "8000m"
    limits:
      memory: "2Gi"
      cpu: "12000m"

    #affinity:
    #  tolerations:
    #    # Allow scheduling on control plane nodes
    #    - key: node-role.kubernetes.io/control-plane
    #      operator: Exists
    #      effect: NoSchedule
    #    - key: storage
    #      operator: Equal
    #      value: "local"
    #      effect: NoSchedule

  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: workload
              operator: In
              values: ["cpu"]

  postgresql:
    parameters:
      # Optimize for limited resources
      shared_buffers: "128MB"
      max_connections: "100"
