apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 5m
  chart:
    spec:
      chart: n8n
      version: 0.23.0
      sourceRef:
        kind: HelmRepository
        name: n8n-oci
        namespace: flux-system
      type: oci
  values:
    persistence:
      enabled: true
      size: 5Gi
      storageClass: openebs-hostpath
    replicaCount: 1
    existingSecret: n8n-postgres-app
    service:
      type: ClusterIP
    ingress:
      enabled: false
