apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-values
  namespace: flux-system
data:
  values.yaml: |
    defaultSettings:
      defaultReplicaCount: 1
      defaultDataPath: /var/lib/longhorn
      replicaAutoBalance: best-effort
      defaultLonghornStaticStorageClass: longhorn
      deletingConfirmationFlag: true

    longhornUI:
      enabled: true

    ingress:
      enabled: true

    service:
      ui:
        type: ClusterIP

    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1
