apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infra-longhorn
  namespace: flux-system
spec:
  interval: 10m
  releaseName: longhorn
  targetNamespace: infra-longhorn
  chart:
    spec:
      chart: longhorn
      version: 1.8.0
      sourceRef:
        kind: HelmRepository
        name: infra-longhorn
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: longhorn-values
      valuesKey: values.yaml
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    podAnnotations:
      promtail.io/scrape: "true"
