---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prometheus-stack-values
  namespace: monitoring
data:
  values.yaml: |
    # Paste the content of k8s-config/monitoring/prometheus/values.yaml here
    defaultRules:
      create: true
    alertmanager:
      enabled: true
      # PERSISTENCE FOR ALERTMANAGER:
      persistence:
        enabled: true
        storageClass: "longhorn" 
        size: 1Gi # Adjust as needed
    grafana:
      enabled: true
      adminPassword: "1234" # Set a secure password for Grafana admin
      # PERSISTENCE FOR GRAFANA:
      persistence:
        enabled: true
        storageClassName: "longhorn" 
        size: 5Gi # Adjust as needed
      ingress:
        enabled: true
        hosts:
          - grafana.yourdomain.com
    prometheus:
      prometheusSpec:
        # PERSISTENCE FOR PROMETHEUS:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: "longhorn" 
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
