---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "72.8.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1h
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-stack-values # This ConfigMap will hold our values.yaml content
      optional: true # Allow this to be optional if you don't need custom values initially
