# infrastructure/infra-cadvisor/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: infra-cadvisor
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: monitoring
  chart:
    spec:
      chart: cadvisor
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: cadvisor
        namespace: flux-system
  values:
    updateStrategy:
      type: Recreate
    image:
      repository: gcr.io/cadvisor/cadvisor
      tag: v0.52.1
      pullPolicy: IfNotPresent
    container:
      port: 8080
      additionalArgs:
        - --housekeeping_interval=10s
        - --max_housekeeping_interval=15s
        - --event_storage_event_limit=default=0
        - --event_storage_age_limit=default=0
        - --disable_metrics=percpu,process,sched,tcp,udp
        - --docker_only
      hostPaths:
        - name: rootfs
          path: "/"
          mount: "/rootfs"
          readOnly: true
        - name: varrun
          path: "/var/run"
          readOnly: true
        - name: sys
          path: "/sys"
          readOnly: true
        - name: docker
          path: "/var/lib/docker"
          readOnly: true
        - name: disk
          path: "/dev/disk"
          readOnly: true
    service:
      type: ClusterIP
      port: 8080
    daemonsetAnnotations:
      seccomp.security.alpha.kubernetes.io/pod: "docker/default"
    priorityClassName: {}
    hostNetwork: false
    serviceAccount:
      create: true
      name: ""
    podSecurityPolicy:
      create: false
      privileged: false
    podSecurityContext:
      create: false
      privileged: false
    metrics:
      enabled: true
      interval: 30s
      scrapeTimeout: 30s
      relabelings:
        - sourceLabels: [container_label_io_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [container_label_io_kubernetes_pod_namespace]
          targetLabel: namespace
        - sourceLabels: [container_label_io_kubernetes_container_name]
          targetLabel: container
