# flux-system/cadvisor-helmrepository.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cadvisor
  namespace: flux-system
spec:
  interval: 1h
  url: https://ckotzbauer.github.io/helm-charts/
