apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-route # Change to the name of the route you want to create
  namespace: monitoring # Change to the namespace where the route should be created
spec:
  parentRefs:
    - name: public-gateway
      namespace: infra-gateway
  hostnames:
    - "g.public.lab.local" # Change to the hostname you want to use
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: / # Change to the path you want to match
      backendRefs:
        - name: monitoring-grafana # Change to the name of the service you want to expose
          port: 80 # Change to the port of the service you want to expose
