apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: harbor-route
  namespace: harbor
  labels:
    app: harbor
    release: harbor
spec:
  parentRefs:
    - name: public-gateway
      namespace: infra-gateway
  hostnames:
    - "harbor.public.lab.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: harbor-portal
          port: 80
