apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - n8n.yaml
  - pgadmin.yaml
  - qdrant.yaml
  - dashy.yaml
  - open-webui.yaml
  - signoz.yaml
  - grafana.yaml
  - prometheus.yaml
  - alertmanager.yaml
  - s3.yaml
