apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: opencost-route
  namespace: monitoring
spec:
  parentRefs:
    - name: public-gateway
      namespace: infra-gateway
  hostnames:
    - "opencost.public.lab.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: opencost
          port: 9003
