apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pgadmin-route
  namespace: pgadmin
spec:
  parentRefs:
    - name: public-gateway
      namespace: infra-gateway
  hostnames:
    - "pgadmin.cluster"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: pgadmin-pgadmin4
          port: 80
