apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: planka-route
  namespace: planka
spec:
  parentRefs:
    - name: public-gateway
      namespace: infra-gateway
  hostnames:
    - "planka.public.lab.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: planka-planka-board
          port: 80
