apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: s3-route
  namespace: rook-ceph
spec:
  parentRefs:
    - name: public-gateway
      namespace: infra-gateway
  hostnames:
    - "s3.cluster"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: rook-ceph-rgw-knowledgebase
          port: 80
