apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: appname-route
  namespace: appnamespace
spec:
  parentRefs:
    - name: public-gateway
      namespace: infra-gateway
  hostnames:
    - "appname.cluster"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: <k8s-service-name>
          port: 80
