# node-patch.yaml
apiVersion: v1
kind: Node
metadata:
  name: talos-cp-01
  labels:
    workload: gpu
spec:
  taints:
    - key: storage
      value: local
      effect: NoSchedule
---
# node-patch.yaml
apiVersion: v1
kind: Node
metadata:
  name: talos-cp-02
  labels:
    workload: cpu
spec:
  taints:
    - key: storage
      value: local
      effect: NoSchedule
