# Patch for the GPU workload node
apiVersion: v1
kind: Node
metadata:
  name: talos-cp-01
  labels:
    workload: gpu
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
spec:
  taints:
    - key: storage
      value: local
      effect: NoSchedule
---
# Patch for the CPU workload node
apiVersion: v1
kind: Node
metadata:
  name: talos-cp-02
  labels:
    workload: cpu
  annotations:
    # Taints are managed through annotations when patching
    node.alpha.kubernetes.io/ttl: "0"
spec:
  taints:
    - key: storage
      value: local
      effect: NoSchedule
