apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  targetNamespace: flux-system
  interval: 10m
  url: https://charts.jetstack.io
