apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-crds
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: v1.14.4
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 10m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
