apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: harbor-planka-repo
  namespace: flux-system
spec:
  interval: 1m
  url: oci://harbor.public.lab.local/helm
  ref:
    tag: latest
  #secretRef:
  #  name: harbor-registry-creds
