apiVersion: helm.toolkit.fluxcd.io/v2 # Use v2 if that's what your Flux version supports
kind: Kustomization
metadata:
  name: planka
  namespace: planka # The namespace where Planka will be deployed (and where the HelmRelease itself resides)
spec: # <--- This is the correct, singular spec block
  interval: 5m # How often Flux should reconcile this HelmRelease
  targetNamespace: planka # The namespace *into which* the Helm chart will be deployed
  releaseName: planka # Recommended: match the HelmRelease name for clarity

  wait: true
  prune: true
  path: "./"
  sourceRef:
    kind: OCIRepository
    name: harbor-planka-repo # The name of the OCIRepository resource that contains your Planka chart

  values:
    planka:
      secretKey: "YOUR_GENERATED_SECURE_SECRET_KEY" # <<-- GENERATE THIS PROPERLY
      baseUrl: "https://planka.public.lab.local" # The base URL for your Planka instance
      admin: # Remember to remove this after first successful deployment!
        email: "oscar@datakube.org"
        username: "admin"
        password: "12345" # <<-- CHANGE THIS
        name: "Planka Admin"
      persistence:
        enabled: true
        storageClass: "longhorn" # Specify your cluster's StorageClass
        size: 2Gi
    postgresql:
      enabled: true
      auth:
        database: planka
        username: planka_user
        password: "12345" # <<-- CHANGE THIS
      primary:
        persistence:
          enabled: true
          storageClass: "longhorn" # Specify your cluster's StorageClass
          size: 5Gi
    ingress:
      enabled: false # Correct, as you're using Cilium Gateway API
      # The rest of the ingress block is effectively ignored because enabled: false
      # However, it's good practice to remove unnecessary fields for clarity
      # className: "nginx"
      # annotations:
      #   cert-manager.io/cluster-issuer: "letsencrypt-prod"
      # hosts:
      #   - host: planka.yourdomain.com
      #     paths:
      #       - path: /
      #         pathType: ImplementationSpecific
      # tls:
      #   - secretName: planka-tls
      #     hosts:
      #       - planka.yourdomain.com
