apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: planka
  namespace: planka
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: harbor-planka-repo
    namespace: flux-system
  values:
    planka:
      secretKey: "YOUR_GENERATED_SECURE_SECRET_KEY"
      baseUrl: "https://planka.public.lab.local"
      admin:
        email: "oscar@datakube.org"
        username: "admin"
        password: "12345"
        name: "Planka Admin"
      persistence:
        enabled: true
        storageClass: "longhorn"
        size: 2Gi
    postgresql:
      enabled: true
      auth:
        database: planka
        username: planka_user
        password: "12345"
      primary:
        persistence:
          enabled: true
          storageClass: "longhorn"
          size: 5Gi
    ingress:
      enabled: false
