apiVersion: source.toolkit.fluxcd.io/v1beta2 # For OCI
kind: HelmRepository
metadata:
  name: harbor-planka-repo
  namespace: flux-system
spec:
  interval: 15m
  url: oci://harbor.public.lab.local/helm
  #secretRef:
  #  name: harbor-registry-creds
