apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: planka
  namespace: planka
spec:
  interval: 10m
  chart:
    spec:
      chart: planka
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: planka
        namespace: flux-system
  values:
    planka:
      secretKey: "YOUR_GENERATED_SECURE_SECRET_KEY"
      baseUrl: "https://planka.public.lab.local"
      admin:
        email: "oscar@datakube.org"
        username: "admin"
        password: "12345"
        name: "Planka Admin"
      persistence:
        enabled: true
        storageClass: "openebs-hostpath"
        size: 2Gi
    postgresql:
      enabled: true
      auth:
        database: planka
        username: planka_user
        password: "12345"
      primary:
        persistence:
          enabled: true
          storageClass: "openebs-hostpath"
          size: 5Gi
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
    ingress:
      enabled: false
    
    # Resource limits for Planka and PostgreSQL
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"
