---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dashy
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://vyrtualsynthese.github.io/selfhosted-helmcharts/
