---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dashy
  namespace: flux-system
spec:
  chart:
    spec:
      chart: dashy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: dashy
        namespace: flux-system
      version: 1.0.0
  targetNamespace: dashy
  interval: 1m0s
  releaseName: dashy
  values:
  configmap:
    enabled: true
    existingConfigMap: dashy-config
