apiVersion: v1
kind: Service
metadata:
  name: kubelet
  namespace: kube-system
  labels:
    k8s-app: kubelet
spec:
  ports:
    - port: 10250
      targetPort: 10250
      protocol: TCP
      name: https-metrics
  clusterIP: None # Headless service to directly reach nodes
