---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: pgadmin
spec:
  interval: 5m
  chart:
    spec:
      chart: pgadmin4
      version: "1.47.0" # Check Artifact Hub for the latest stable version
      sourceRef:
        kind: HelmRepository
        name: runix-charts
        namespace: flux-system
  values:
    # Node selector to deploy pgAdmin specifically on talos-worker-01
    nodeSelector:
      kubernetes.io/hostname: talos-worker-01

    # Persistence for pgAdmin configuration and saved connections
    persistentVolume:
      enabled: true
      storageClass: openebs-hostpath
      size: 1Gi # Adjust size as needed

    # Service type - ClusterIP is sufficient as Cilium HTTPRoute will expose it
    service:
      type: ClusterIP
      port: 80

    # Resource limits and security context
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    
    securityContext:
      runAsNonRoot: true
      runAsUser: 5050
      runAsGroup: 5050
      fsGroup: 5050

  # Use valuesFrom to inject secret data directly into chart values
  valuesFrom:
    - kind: Secret
      name: pgadmin-credentials
      valuesKey: PGADMIN_DEFAULT_EMAIL
      targetPath: env.email # Maps to .Values.env.email in the chart
    - kind: Secret
      name: pgadmin-credentials
      valuesKey: PGADMIN_DEFAULT_PASSWORD
      targetPath: env.password # Maps to .Values.env.password in the chart

