---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-credentials
  namespace: pgadmin
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: admin@example.com # CHANGE THIS
  PGADMIN_DEFAULT_PASSWORD: supersecretpassword # CHANGE THIS
