apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prom-stack
  namespace: prom-stack
spec:
  interval: 30m
  timeout: 10m
  chartRef:
    kind: OCIRepository
    name: prom-stack-oci
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: prom-stack-values
  values:
    # Storage configuration for Prometheus
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: rook-ceph-block-retain
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi

        # Set retention to match storage size
        retention: 30d
        retentionSize: 45GiB

        # Resource limits for production use
        resources:
          requests:
            memory: 2Gi
            cpu: 500m
          limits:
            memory: 4Gi
            cpu: 1000m

    # Storage configuration for Alertmanager
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: rook-ceph-block-retain
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi

        # Resource limits
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 200m

    # Grafana persistence
    grafana:
      persistence:
        enabled: true
        type: pvc
        storageClassName: rook-ceph-block-retain
        accessModes:
          - ReadWriteOnce
        size: 10Gi
        finalizers:
          - kubernetes.io/pvc-protection

      # Resource limits for Grafana
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 200m

    # Node exporter resource limits
    prometheus-node-exporter:
      resources:
        requests:
          memory: 30Mi
          cpu: 50m
        limits:
          memory: 50Mi
          cpu: 100m

    # Kube-state-metrics resource limits
    kube-state-metrics:
      resources:
        requests:
          memory: 64Mi
          cpu: 50m
        limits:
          memory: 128Mi
          cpu: 100m

    # Prometheus operator resource limits
    prometheusOperator:
      resources:
        requests:
          memory: 64Mi
          cpu: 50m
        limits:
          memory: 128Mi
          cpu: 100m
