apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prom-stack-oci
  namespace: flux-system
spec:
  interval: 30m
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
  ref:
    semver: "*"
