apiVersion: batch/v1
kind: Job
metadata:
  name: delete-kube-proxy
  namespace: kube-system
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: nuker
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "[+] Deleting kube-proxy DS and ConfigMap..."
              kubectl delete daemonset kube-proxy -n kube-system --ignore-not-found
              kubectl delete configmap kube-proxy -n kube-system --ignore-not-found
