apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infra-node-exporter
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-node-exporter
      version: 4.45.3
      sourceRef:
        kind: HelmRepository
        name: infra-node-exporter
        namespace: flux-system
  targetNamespace: monitoring
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    hostNetwork: false
    hostPID: false
    hostPort:
      enabled: false
    extraArgs:
      - --no-collector.filesystem
      - --no-collector.mountstats
      - --no-collector.netclass
      - --no-collector.netdev

    # (Optional but recommended to nuke auto-mounts completely)
    volumeMounts: []
    volumes: []

    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
    service:
      port: 9100
    prometheus:
      monitor:
        enabled: true
    rbac:
      create: true
    serviceAccount:
      create: true
    securityContext:
      runAsUser: 65534
      runAsGroup: 65534
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
    podSecurityContext:
      runAsUser: 65534
      fsGroup: 65534
    hostRootFsMount:
      enabled: false # turn OFF unsafe host mounts
    collectors:
      disabled:
        - hwmon
        - mdadm
        - edac
        - timex
        - systemd
        - interrupts
