apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infra-node-exporter
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-node-exporter
      version: 4.45.3
      sourceRef:
        kind: HelmRepository
        name: infra-node-exporter
        namespace: flux-system
  targetNamespace: monitoring
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    hostNetwork: false
    hostPID: false
    hostIPC: false
    hostRootFsMount:
      enabled: false
    hostProcFsMount:
      mountPropagation: ""
    hostSysFsMount:
      mountPropagation: ""

    rbac:
      create: true
      pspEnabled: false # 🚨 turn off old PodSecurityPolicy stuff

    securityContext:
      fsGroup: 65534
      runAsGroup: 65534
      runAsNonRoot: true
      runAsUser: 65534

    containerSecurityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL

    tolerations:
      - operator: Exists

    volumeMounts: [] # 🚨 force empty to block /proc, /sys mounts
    volumes: [] # 🚨 force empty to block any mounts

    extraArgs: # Optional hardening: disable collectors needing deep /proc
      - --no-collector.filesystem
      - --no-collector.hwmon
      - --no-collector.mdadm
      - --no-collector.edac
      - --no-collector.timex
      - --no-collector.systemd
      - --no-collector.interrupts

    service:
      enabled: true
      port: 9100
      annotations:
        prometheus.io/scrape: "true"

    prometheus:
      monitor:
        enabled: true
        scrapeTimeout: 10s
        scheme: http
