apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-database
provisioner: openebs.io/localpv-device
volumeBindingMode: Immediate
reclaimPolicy: Delete
allowVolumeExpansion: true
