apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-local-disk
provisioner: openebs.io/localpv-device
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
