apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: ai-workload
spec:
  targetNamespace: ai-workload
  interval: 10m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.17.2
      sourceRef:
        kind: HelmRepository
        name: nvidia-device-plugin
        namespace: flux-system
  values:
    nodeSelector: # This will apply to the DaemonSet's pod template
      kubernetes.io/hostname: talos-cp-01
    tolerations: # This will apply to the DaemonSet's pod template
      - key: "storage"
        operator: "Equal"
        value: "local"
        effect: "NoSchedule"
