---
- name: Install and enable iSCSI across cluster
  hosts: all
  become: yes

  tasks:
    - name: Install iSCSI
      pacman:
        name: open-iscsi
        state: present
        update_cache: yes

    - name: Enable and start iscsid
      systemd:
        name: iscsid
        enabled: yes
        state: started

    - name: Verify iSCSI service status
      command: systemctl is-active iscsid
      register: iscsi_status
      changed_when: false

    - debug:
        msg: "iSCSI service is {{ iscsi_status.stdout }}"
