apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infra-vl
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: monitoring
  chart:
    spec:
      chart: victoria-logs-single
      version: 0.9.7
      sourceRef:
        kind: HelmRepository
        name: infra-victoria-logs
        namespace: flux-system
  values:
    fullnameOverride: vl
    nameOverride: vl
    statefulset:
      name: vl
    persistence:
      enabled: true
      existingClaim: victorialogs-pvc
    service:
      type: ClusterIP
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    server:
      extraArgs:
        loggerLevel: ERROR
        retentionPeriod: 30d
