apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: infra-victoria-logs
  namespace: flux-system
spec:
  interval: 1h
  url: https://victoriametrics.github.io/helm-charts/

