apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infra-vm
  namespace: flux-system
spec:
  targetNamespace: monitoring
  interval: 5m
  chart:
    spec:
      chart: victoria-metrics-single
      version: 0.17.1
      sourceRef:
        kind: HelmRepository
        name: infra-victoria-logs
        namespace: flux-system
  values:
    server:
      extraArgs:
        httpListenAddr: ":8428"
        loggerLevel: ERROR
        envflag.enable: "true"
        promscrape.config: "/config/prometheus.yml"
        retentionPeriod: "30d"

      extraVolumeMounts:
        - name: scrape-config
          mountPath: /config

      extraVolumes:
        - name: scrape-config
          configMap:
            name: vm-scrape-config

      retentionPeriod: 3 # 3 days Modified to see if the network spike is related to the retention period

      persistentVolume:
        enabled: true
        storageClass: longhorn
        size: 10Gi
      service:
        type: ClusterIP
