apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-controller-monitoring-crds
rules:
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["servicemonitors", "podmonitors"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-controller-monitoring-crds
roleRef:
  kind: ClusterRole
  name: helm-controller-monitoring-crds
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: helm-controller
    namespace: flux-system
