apiVersion: v1
kind: ConfigMap
metadata:
  name: vm-scrape-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:

      - job_name: 'cadvisor'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
            regex: cadvisor
            action: keep
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node
          - source_labels: [__address__]
            target_label: __address__
        metricRelabelConfigs:
          - sourceLabels: [id]
            regex: '^/kubepods[^/]+/pod[^/]+/(.+)$'
            targetLabel: container_id
            replacement: '$1'
          - sourceLabels: [container_label_io_kubernetes_pod_name]
            targetLabel: pod
          - sourceLabels: [container_label_io_kubernetes_pod_namespace]
            targetLabel: namespace
          - sourceLabels: [container_label_io_kubernetes_container_name]
            targetLabel: container

      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: keep
            source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
            regex: monitoring-infra-node-exporter
          - action: keep
            source_labels: [__meta_kubernetes_namespace]
            regex: monitoring
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            regex: (.*)
            replacement: ${1}:9100
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: instance
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
