apiVersion: v1
kind: ConfigMap
metadata:
  name: vm-scrape-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:

      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: keep
            source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
            regex: monitoring-infra-node-exporter
          - action: keep
            source_labels: [__meta_kubernetes_namespace]
            regex: monitoring
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            regex: (.*)
            replacement: ${1}:9100
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: instance
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)

      - job_name: 'kube-state-metrics'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: keep
            source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            regex: kube-state-metrics
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            regex: (.*)
            replacement: ${1}:8080

      - job_name: 'etcd'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: keep
            source_labels: [__meta_kubernetes_pod_label_component]
            regex: etcd
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            regex: (.*)
            replacement: ${1}:2379

      - job_name: 'kubelet-cadvisor'
        scheme: https
        kubernetes_sd_configs:
          - role: node
        tls_config:
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        metrics_path: /metrics/cadvisor
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: instance
            source_labels: [__meta_kubernetes_node_name]
