apiVersion: v1
kind: ConfigMap
metadata:
  name: vm-scrape-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: keep
            source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            regex: prometheus-node-exporter
          - action: keep
            source_labels: [__meta_kubernetes_namespace]
            regex: monitoring
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: $1:9100
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
