apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public-gateway
  namespace: infra-gateway
spec:
  addresses:
    - type: IPAddress
      value: 192.168.68.15
  gatewayClassName: cilium
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      name: http
      hostname: "*.cluster"
      port: 80
      protocol: HTTP

    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.cluster"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: cfe-tls-key-pair
