apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public-gateway
  namespace: infra-gateway
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 192.168.178.240
  listeners:
    - name: http
      hostname: "*.public.lab.local"
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
