apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-values
  namespace: harbor
data:
  values.yaml: |
    expose:
      type: clusterIP
      ingress:
        hosts: 
          core: harbor.public.lab.local 
          notary: harbor.public.lab.local 
      tls:
        enabled: false 
        certSource: auto 
    authMode: db_auth 
    ldap:
      enabled: false
    oidc:
      enabled: false
    externalURL: https://harbor.public.lab.local 
    persistence:
      enabled: true
      resourcePolicy: "keep" 

      persistentVolumeClaim:
        registry:
          existingClaim: harbor-registry
        jobservice:
          existingClaim: harbor-jobservice
        database:
          existingClaim: database-data-harbor-database-0
        redis:
          existingClaim: data-harbor-redis-0
        trivy:
          existingClaim: data-harbor-trivy-0

      imageChartStorage:
        type: filesystem
        storageClass: "longhorn" 
        size: 50Gi 
      database:
        persistence:
          enabled: true
          resourcePolicy: "keep"
          storageClass: "longhorn" 
          size: 5Gi 
          accessMode: ReadWriteOnce
      redis:
        persistence:
          enabled: true
          resourcePolicy: "keep"
          storageClass: "longhorn" 
          size: 1Gi 
          accessMode: ReadWriteOnce
      jobservice:
        jobLog:
          persistence:
            enabled: true
            resourcePolicy: "keep"
            storageClass: "longhorn" 
            size: 1Gi 
            accessMode: ReadWriteOnce
      clair:
        enabled: true
        persistence:
          enabled: true 
          resourcePolicy: "keep"
          storageClass: "longhorn" 
          size: 5Gi 
      trivy:
        enabled: true
        persistence:
          enabled: true 
          storageClass: "longhorn" 
          size: 5Gi 
    existingSecretSecretPasswordKey: HARBOR_ADMIN_PASSWORD
    harborAdminPassword: "12345"

    internalTLS:
      enabled: false

    portal:
      replicaCount: 1
      image:
        tag: v2.13.1
    core:
      replicaCount: 1
      image:
        tag: v2.13.1
    jobservice:
      replicaCount: 1
      image:
        tag: v2.13.1
    registry:
      replicaCount: 1
      registry:
        image:
          tag: v2.13.1
      controller:
        image:
          tag: v2.13.1
    database:
      replicaCount: 1
      internal:
        image:
          tag: v2.13.1
        password: "changeit" # Password for internal Postgres user
    redis:
      replicaCount: 1
      internal:
        image:
          tag: v2.13.1
    exporter:
      replicaCount: 1
      image:
        tag: v2.13.1
    trivy:
      replicaCount: 1
      image:
        tag: v2.13.1 
    clair:
      replicaCount: 1
      image:
        tag: v2.13.1 

    # --- Disable optional features for a leaner local registry ---
    metrics:
      enabled: false

    # The secret key for encryption. Must be a string of 16 chars.
    secretKey: "6035937314011719" # e.g., "abcdefghijklmnop"

    # Log level for components
    logLevel: info
