apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-values
  namespace: harbor
data:
  values.yaml: |
    expose:
      type: ingress
    ingress:
      hosts: 
        core: harbor.public.lab.local 
        notary: harbor.public.lab.local 
      tls:
        enabled: true 
        certSource: auto 
    authMode: db_auth 
    ldap:
      enabled: false
    oidc:
      enabled: false
    externalURL: https://harbor.public.lab.local 
    persistence:
      enabled: true
      resourcePolicy: "" 
      imageChartStorage:
        type: filesystem
        storageClass: "longhorn" # Use your Longhorn StorageClass
        size: 50Gi # Adjust size as needed
      database:
        persistence:
          enabled: true
          resourcePolicy: ""
          storageClass: "longhorn" # Use Longhorn for database
          size: 5Gi # Adjust size as needed
          accessMode: ReadWriteOnce
      redis:
        persistence:
          enabled: true
          resourcePolicy: ""
          storageClass: "longhorn" # Use Longhorn for Redis
          size: 1Gi # Adjust size as needed
          accessMode: ReadWriteOnce
      jobservice:
        jobLog:
          persistence:
            enabled: true
            resourcePolicy: ""
            storageClass: "longhorn" # Use Longhorn for job logs
            size: 1Gi # Adjust size as needed
            accessMode: ReadWriteOnce
      trivy:
        persistence:
          enabled: false 
          # Disable Trivy persistence if Trivy is disabled
          # storageClass: "longhorn" # Only specify if enabled
          # size: 5Gi # Only specify if enabled
    harborAdminPassword: "12345"

    internalTLS:
      enabled: false

    portal:
      image:
        tag: v2.13.1
    core:
      image:
        tag: v2.13.1
    jobservice:
      image:
        tag: v2.13.1
    registry:
      registry:
        image:
          tag: v2.13.1
      controller:
        image:
          tag: v2.13.1
    database:
      internal:
        image:
          tag: v2.13.1
        password: "changeit" # Password for internal Postgres user
    redis:
      internal:
        image:
          tag: v2.13.1
    exporter:
      image:
        tag: v2.13.1
    trivy:
      image:
        tag: v2.13.1 # Only relevant if trivy.enabled is true

    # --- Disable optional features for a leaner local registry ---
    metrics:
      enabled: false
    trivy:
      enabled: false # Disable vulnerability scanning for simpler setup
    # If you later enable Trivy, make sure `trivy.persistence.enabled` above is also `true`
    # and its `storageClass` and `size` are set.

    # --- Other important settings ---
    # The secret key for encryption. Must be a string of 16 chars.
    # IMPORTANT: CHANGE THIS TO A RANDOM 16-character string!
    secretKey: "6035937314011719" # e.g., "abcdefghijklmnop"
    # Or use existingSecretSecretKey if managed via a secret.
    # existingSecretSecretKey: ""

    # Log level for components
    logLevel: info
