apiVersion: helm.toolkit.fluxcd.io/v2

kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: "1.17.1"
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: harbor-values
      optional: false
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
    timeout: 10m
  test:
    enable: true
  timeout: 15m
