apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls
  namespace: hypercube-test
spec:
  secretName: wildcard-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - HyperCube Org
  commonName: "*.public.lab.local" # Wildcard common name
  dnsNames:
    - "*.public.lab.local"
    - "public.lab.local" # Include the base domain as well
  issuerRef:
    name: selfsigned-cluster-issuer # Or your preferred issuer
    kind: ClusterIssuer
