---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-stack-values
  namespace: monitoring
data:
  values.yaml: |
    # Paste the content of k8s-config/monitoring/loki/values.yaml here
    grafana:
      enabled: false
    loki:
      # PERSISTENCE FOR LOKI:
      persistence:
        enabled: true
        storageClassName: "longhorn" 
        size: 10Gi 
        accessModes:
          - ReadWriteOnce
    promtail:
      enabled: true
