apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - helmrepo.yaml
  - values.yaml
  - config.yaml
  - storage-class.yaml
  - storage-class-retain.yaml
  - pool.yaml
  - rdw.yaml
  - rdw-user.yaml
