apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph-details
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/kind/rook-ceph-details
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: rook-ceph
