apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-state-metrics
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "*"
  values:
    replicas: 1
    prometheus:
      monitor:
        enabled: false
    podAnnotations:
      checksum/config: ""
