{{- if .Values.ingress.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.app.name }}-route
  namespace: {{ .Values.app.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
spec:
  parentRefs:
    - name: public-gateway
      namespace: infra-gateway
  hostnames:
    - {{ .Values.ingress.hostname | default (printf "%s.cluster" .Values.app.name) }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: {{ .Values.app.name }}
          port: 80
{{- end }}