---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: flux-system
spec:
  chart:
    spec:
      chart: open-webui
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: flux-system
      version: 7.7.0
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: open-webui
  targetNamespace: open-webui
  values:
    # Enable Ollama and Pipelines
    ollama:
      enabled: false
      fullnameOverride: "open-webui-ollama"

    ollamaUrls:
      - "http://192.168.68.50:11434"

    pipelines:
      enabled: true

      # Add any specific pipeline environment variables you need
      extraEnvVars:
        - name: N8N_WEBHOOK_URL
          value: "http://n8n.n8n/webhook"

      persistence:
        enabled: true
        existingClaim: open-webui-pipelines-pvc

    # Basic service configuration
    service:
      type: ClusterIP
      port: 80
      containerPort: 8080

    # Persistence for data
    persistence:
      enabled: true
      #size: 5Gi
      #storageClass: rook-ceph-block
      existingClaim: open-webui-base-pvc

    # Environment variables
    extraEnvVars:
      - name: OPENAI_API_KEY
        value: "0p3n-w3bu!"
      # Add N8N integration if needed
      - name: WEBHOOK_URL
        value: "http://open-webui-pipelines:9099"

    # Enable OpenAI API compat
    enableOpenaiApi: true
    openaiBaseApiUrl: "http://open-webui-pipelines:9099"

    # Resource limits
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
